name: "Lint app"
description: "Run eslint on the frontend and backend"

runs:
  using: "composite"
  steps:
    - name: Run frontend lint
      shell: bash
      run: npm -w frontend run lint
    - name: Run backend lint
      shell: bash
      run: npm -w backend run lint
