name: "Install dependencies"
description: "Install dependencies for the project"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      if: always()
      id: restore-cache
      with:
        path: |
          **/node_modules
          packages/types/dist
          packages/frontend/src/redux/api/generated/*.ts
        key: ${{ runner.os }}-modules-${{ hashFiles('./package-lock.json') }}-${{ hashFiles('./packages/types/src/*') }}-${{ hashFiles('./packages/frontend/src/redux/schema/api-spec.json') }}
    - name: Install dependencies
      if: steps.restore-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
