name: "Install dependencies"
description: "Install dependencies for the project and cache cypress binaries"

runs:
  using: "composite"
  steps:
    - name: Copy package-lock for cypress action
      shell: bash
      run: cp package-lock.json ./packages/cypress/package-lock.json
    - name: Install dependencies
      if: steps.modules-cache.outputs.cache-hit != 'true'
      uses: cypress-io/github-action@v2
      with:
        runTests: false
        working-directory: packages/cypress
        install-command: npm ci --prefix ../../
