name: "Install dependencies"
description: "Install dependencies for the project and cache cypress binaries"

runs:
  using: "composite"
  steps:
    - name: remove cache cypress
      run: rm -rf packages/cypress/node_modules node_modules
      shell: bash
    - name: Install dependencies
      shell: bash
      run: npm ci
