{{- $namespace := printf "%s" .Values.namespace }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-volume
  namespace: {{ $namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
