{{- $namespace := printf "%s" .Values.namespace }}


apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initial-config
  namespace: {{ $namespace }}
data:
  init-users.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
      CREATE DATABASE $POSTGRES_DB;
      GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
    EOSQL
