{{- $namespace := printf "%s" .Values.namespace }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: scheduled-transactions
  namespace: {{ $namespace }}
spec:
  schedule: {{ .Values.scheduledTransactions.schedule }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: create-transaction-from-templates
              image: appropriate/curl
              args:
                - /bin/sh
                - -c
                - |
                  echo "Starting transaction creation.."
                  RESPONSE=$(curl -so /dev/null -w '%{response_code}' {{ .Values.scheduledTransactions.endpoint }})
                  if [ $RESPONSE == 200 ]; then
                          echo "Transaction created, response code: ${RESPONSE}"
                  else
                          echo "Failed to create transactions, response code: ${RESPONSE}"
                  fi
          restartPolicy: Never
