name: Playwright Tests
description: Run Playwright tests

runs:
  using: "composite"
  steps:
    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      shell: bash
      run: cd packages/playwright && npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
