name: Playwright Tests
description: Run Playwright tests

inputs:
  SHARD:
    description: "Shard number e.g. 1"
    required: true
  SHARD_COUNT:
    description: "Total number of shards e.g. 5"
    required: true

runs:
  image: docker://mcr.microsoft.com/playwright:v1.48.2
  using: "docker"
  steps:
    - name: Run Playwright tests
      shell: bash
      run: npm run e2e:test -- --shard ${{ inputs.SHARD }}/${{ inputs.SHARD_COUNT }}

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-blob-shard-${{ inputs.SHARD }}
        path: packages/playwright/blob-report/
        retention-days: 7
