name: Playwright Tests
description: Run Playwright tests

inputs:
  target-project:
    description: "The project to run the tests on"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Playwright Browsers
      shell: bash
      run: |
        if [ "${{ inputs.target-project }}" = "chromium" ] || [ "${{ inputs.target-project }}" = "Mobile_Chrome" ]; then
          npx playwright install --with-deps chromium
        elif [ "${{ inputs.target-project }}" = "firefox" ]; then
          npx playwright install --with-deps firefox
        elif [ "${{ inputs.target-project }}" = "webkit" ] || [ "${{ inputs.target-project }}" = "Mobile_Safari" ]; then
          npx playwright install --with-deps webkit
        fi
    - name: Run Playwright tests
      shell: bash
      run: npm run e2e:test -- --project=${{ inputs.target-project }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: packages/playwright/playwright-report/
        retention-days: 30
