name: "Cache build"
description: "Cache app build"

outputs:
  cache-hit:
    description: "true/false if build was cached"
    value: "{{ steps.cache-build.outputs.cache-hit }}"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      id: cache-build
      with:
        path: "./build"
        key: ${{ runner.os }}-build-${{ hashFiles('./package-lock.json') }}-${{ hashFiles('./packages/backend/**') }}-${{ hashFiles('./packages/frontend/**') }}-${{ hashFiles('./packages/types/**') }}
