services:
  postgres:
    image: postgres:latest
    hostname: postgres
    restart: always
    container_name: financer_dev-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=financer_dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=change-me
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U admin -d financer_dev"]
    #   interval: 10s
    #   start_period: 30s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: financer_dev-pgadmin
    hostname: pgadmin
    environment:
      - PGADMIN_CONFIG_SERVER_MODE=False
      - MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_DEFAULT_EMAIL=admin@financer
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
    ports:
      - 3300:80
    volumes:
      - ./pgadmin-config/servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
    name: financer_dev-postgresdata
