version: "3.6"
# Deploys MongoDB with customization scripts and container with Mongo client
# https://fabianlee.org/2018/05/20/docker-using-docker-compose-to-link-a-mongodb-server-and-client/
#
# usage:
# sudo docker-compose build
# sudo docker-compose up

services:
  mongodb:
    image: mongo:4.2.10-bionic
    hostname: mongodb
    restart: always
    container_name: financer_dev-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=financer_dev
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=change-me
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u admin -p change-me --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: ["--replSet", "rs0", "--bind_ip_all"]

  mongodbclient:
    image: mongo-express:latest
    container_name: financer_dev-mongoclient
    hostname: mongoclient
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_DATABASE=financer_dev
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=change-me
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    ports:
      - 3300:8081

volumes:
  mongo_data:
    name: financer_dev-mongodata
  mongo_config:
    name: financer_dev-mongoconfig
