name: "Build"
description: "Build the application"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      id: restore-cache
      with:
        path: "./build/backend"
        key: ${{ runner.os }}-build-${{ hashFiles('./package-lock.json') }}-${{ hashFiles('!./packages/backend/**/*.spec.*', '!./packages/backend/**/*.test.*', './packages/backend/**') }}

    - name: Build app
      if: steps.restore-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ./build
        rm -rf ./build/backend
        npm run build:backend
