name: "Build"
description: "Build the application"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      id: restore-cache
      with:
        path: "./build"
        key: ${{ runner.os }}-build-${{ hashFiles('./package-lock.json') }}-${{ hashFiles('./packages/backend/**') }}-${{ hashFiles('./packages/frontend/**') }} }}

    - name: Build app
      if: steps.restore-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm run build
