export enum UserPreferenceProperty {
  DEFAULT_INCOME_ACCOUNT = 'DEFAULT_INCOME_ACCOUNT',
  DEFAULT_EXPENSE_ACCOUNT = 'DEFAULT_EXPENSE_ACCOUNT',
  DEFAULT_TRANSFER_SOURCE_ACCOUNT = 'DEFAULT_TRANSFER_SOURCE_ACCOUNT',
  DEFAULT_TRANSFER_TARGET_ACCOUNT = 'DEFAULT_TRANSFER_TARGET_ACCOUNT',
  TRANSACTION_LIST_CHUNK_SIZE = 'TRANSACTION_LIST_CHUNK_SIZE',
  UPDATE_INVESTMENT_MARKET_VALUE = 'UPDATE_INVESTMENT_MARKET_VALUE',
}
