apiVersion: v1
kind: Namespace
metadata:
  name: financer

---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-environment-secret
  namespace: financer
type: Opaque
stringData:
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  AUTH0_DOMAIN: ""
  AUTH0_CLIENT_ID: ""
  AUTH0_CLIENT_SECRET: ""
  DB_USER: admin
  DB_PASSWORD: change-me
  DB_NAME: financer
  DB_HOST: mongodb:27017

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-environment-config
  namespace: financer
data:
  PUBLIC_URL: https://financer.silte.fi
  COOKIE_KEY: financer-production

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-crentials-secret
  namespace: financer
type: Opaque
stringData:
  MONGO_INITDB_DATABASE: financer
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: change-me

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials-secret
  namespace: financer
type: Opaque
stringData:
  POSTGRES_DB: financer
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: change-me
