apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: financer
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-backup
              image: postgres:17-alpine
              args:
                - "/bin/sh"
                - "-c"
                - 'PGPASSWORD=$DB_PASSWORD pg_dump -U $DB_USER -h $DB_HOST -d $DB_NAME -F c -b -v -f /backup/financer_$(date +"%Y-%m-%d_%H-%M").backup'
              envFrom:
                - secretRef:
                    name: webapp-environment-secret
              volumeMounts:
                - name: backup-volume
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: postgres-backup-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-volume
  namespace: financer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
