apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: financer
  labels:
    name: webapp
    env: productions
    app: financer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: ghcr.io/sebarickert/financer:latest
          command: ["node", "backend/main.js"]
          name: backend
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"
          ports:
            - containerPort: 4000
              name: backend
          envFrom:
            - secretRef:
                name: webapp-environment-secret
            - configMapRef:
                name: webapp-environment-config
          livenessProbe:
            httpGet:
              path: /health-check/ping
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /health-check/ping
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10

        - image: ghcr.io/sebarickert/financer:latest
          command: ["node", "frontend/server.js"]
          name: frontend
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"
          ports:
            - containerPort: 3000
              name: frontend
          env:
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
          livenessProbe:
            httpGet:
              path: /healthz/
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /healthz/
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: financer
  name: financer
  labels:
    app: financer
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: frontend
    - port: 81
      targetPort: 4000
      name: backend
    - port: 88
      targetPort: 4001
      name: dummy
  selector:
    app: webapp

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: financer
  namespace: financer
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
    - host: financer.silte.fi
      http:
        paths:
          - path: /api/tasks
            pathType: Prefix
            backend:
              service:
                name: financer
                port:
                  number: 88
    - host: financer.silte.fi
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: financer
                port:
                  number: 81
    - host: financer.silte.fi
      http:
        paths:
          - path: /auth/
            pathType: Prefix
            backend:
              service:
                name: financer
                port:
                  number: 81
    - host: financer.silte.fi
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: financer
                port:
                  number: 80
