name: "Build"
description: "Build the application"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      id: restore-cache
      with:
        path: "./build/frontend"
        key: ${{ runner.os }}-build-${{ hashFiles('./package-lock.json') }}-${{ hashFiles('!./packages/frontend/**/*.spec.*', '!./packages/frontend/**/*.test.*', './packages/frontend/**') }}

    - name: Build app
      if: steps.restore-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        rm -rf ./build/frontend
        mkdir -p ./build
        npm run build:frontend
