name: "Run cypress tests"
description: "Run cypress tests"

inputs:
  cypress-spec-folder:
    description: "The folder containing the cypress tests"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run cypress
      uses: cypress-io/github-action@v4
      with:
        install: false
        working-directory: packages/cypress
        spec: cypress/integration/${{ inputs.cypress-spec-folder }}/**
        start: npm run start:ci --prefix ../../
        wait-on: "http://localhost:3000"
        wait-on-timeout: 120
        headless: true
        config: video=false,screenshotOnRunFailure=false,defaultCommandTimeout=15000,requestTimeout=15000
