name: Build and publish docker

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      REGISTERY_TOKEN:
        description: "The docker registery token"
        required: true
      DOCKER_TARGET_PLATFORMS:
        description: "The docker target platforms"
        required: false

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTERY_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up tags
        id: build-tags
        shell: bash
        env:
          REGISTRY: ghcr.io/${{ github.repository_owner }}
          REPOSITORY: financer
        run: |
          IMAGE_NAME=$REGISTRY/$REPOSITORY
          echo "COMMIT_REF=${IMAGE_NAME}:$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "BUILD_NUMBER=${IMAGE_NAME}:${{ github.run_number }}" >> $GITHUB_OUTPUT
            echo "LATEST=${IMAGE_NAME}:latest" >> $GITHUB_OUTPUT
          else
            echo "BUILD_NUMBER=${IMAGE_NAME}:dev-${{ github.run_number }}" >> $GITHUB_OUTPUT
            echo "LATEST=${IMAGE_NAME}:latest-dev" >> $GITHUB_OUTPUT
          fi

      - name: Build and publish
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ secrets.DOCKER_TARGET_PLATFORMS || 'linux/amd64,linux/arm64' }}
          push: true
          file: ./docker/Dockerfile
          tags: |
            ${{ steps.build-tags.outputs.BUILD_NUMBER }}
            ${{ steps.build-tags.outputs.COMMIT_REF }}
            ${{ steps.build-tags.outputs.LATEST }}
