name: Build and deploy dev

on:
  workflow_dispatch:

concurrency:
  group: ci-build_dev_${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: serkfi/financer/.github/actions/prepare-node-job@main

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: serkfi/financer/.github/actions/prepare-node-job@main

      - uses: serkfi/financer/.github/actions/lint-app@main

  lint-type:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: serkfi/financer/.github/actions/prepare-node-job@main

      - name: Lint TS types
        run: npm run check-types

  unit-test-frontend:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: serkfi/financer/.github/actions/prepare-node-job@main

      - uses: serkfi/financer/.github/actions/test-frontend@main

  unit-test-backend:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: serkfi/financer/.github/actions/prepare-node-job@main

      - uses: serkfi/financer/.github/actions/test-backend@main

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: serkfi/financer/.github/actions/prepare-node-job@main

      - uses: serkfi/financer/.github/actions/build-app@main

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Expose GitHub Runtime
        id: runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - uses: serkfi/financer/.github/actions/build-docker-image@main
        with:
          REGISTRY_TOKEN: ${{ secrets.REGISTERY_TOKEN }}
        env:
          ACTIONS_CACHE_URL: ${{ steps.runtime.outputs.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ steps.runtime.outputs.ACTIONS_RUNTIME_TOKEN }}

  docker-publish:
    needs:
      - docker-build
      - lint
      - lint-type
      - unit-test-frontend
      - unit-test-backend
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Expose GitHub Runtime
        id: runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - uses: serkfi/financer/.github/actions/publish-docker-image@main
        with:
          REGISTRY_TOKEN: ${{ secrets.REGISTERY_TOKEN }}
        env:
          ACTIONS_CACHE_URL: ${{ steps.runtime.outputs.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ steps.runtime.outputs.ACTIONS_RUNTIME_TOKEN }}
