name: Validate Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-build_${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: serkfi/financer/.github/actions/prepare-node-job@main

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: serkfi/financer/.github/actions/prepare-node-job@main

      - uses: serkfi/financer/.github/actions/lint-app@main

  unit-test-frontend:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: serkfi/financer/.github/actions/prepare-node-job@main

      - uses: serkfi/financer/.github/actions/test-frontend@main

  unit-test-backend:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: serkfi/financer/.github/actions/prepare-node-job@main

      - uses: serkfi/financer/.github/actions/test-backend@main

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: serkfi/financer/.github/actions/prepare-node-job@main

      - uses: serkfi/financer/.github/actions/build-app@main

  run-e2e-test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        spec: [
            "chromium",
            # "firefox",
            # "webkit",
            "Mobile_Chrome",
            # "Mobile_Safari"
          ]
    steps:
      - uses: serkfi/financer/.github/actions/prepare-node-job@main

      - uses: serkfi/financer/.github/actions/build-app@main

      - uses: serkfi/financer/.github/actions/test-playwright@main
        with:
          target-project: ${{ matrix.spec }}
