name: Validate Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-build_${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: sebarickert/financer/.github/actions/prepare-node-job@test-setup

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: sebarickert/financer/.github/actions/prepare-node-job@test-setup

      - uses: sebarickert/financer/.github/actions/lint-app@test-setup

  lint-type:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: sebarickert/financer/.github/actions/prepare-node-job@test-setup

      - name: Lint TS types
        run: npm run check-types

  test-frontend:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: sebarickert/financer/.github/actions/prepare-node-job@test-setup

      - uses: sebarickert/financer/.github/actions/test-jest@test-setup
        with:
          PACKAGE_ROOT: "packages/frontend"

  test-backend:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: sebarickert/financer/.github/actions/prepare-node-job@test-setup

      - uses: sebarickert/financer/.github/actions/test-jest@test-setup
        with:
          PACKAGE_ROOT: "packages/backend"

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: sebarickert/financer/.github/actions/prepare-node-job@test-setup

      - uses: sebarickert/financer/.github/actions/build-app@test-setup

  run-e2e-tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: sebarickert/financer/.github/actions/prepare-node-job@test-setup

      - uses: sebarickert/financer/.github/actions/build-app@test-setup

      - name: Run end-to-end tests
        uses: sebarickert/financer/.github/actions/test-playwright@test-setup
        with:
          SHARD: ${{ matrix.shard }}
          SHARD_COUNT: 5
        env:
          INITIALIZE_SCHEMA_AND_TEST_USER: true
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_NAME: testdb-${{ matrix.shard }}

  merge-reports:
    if: always()
    needs: run-e2e-tests

    runs-on: ubuntu-latest
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: playwright-blob-reports
          pattern: playwright-blob-shard-*
          delete-merged: true

      - uses: sebarickert/financer/.github/actions/prepare-node-job@test-setup

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          name: playwright-blob-reports
          path: playwright-blob-reports

      - name: Merge into Playwright reports
        run: npx playwright merge-reports --reporter html,github ./playwright-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14

  static-analyze-frontend:
    needs:
      - test-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: sebarickert/financer/.github/actions/static-analyze@test-setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PACKAGE_ROOT: "packages/frontend"

  static-analyze-backend:
    needs:
      - test-backend
    runs-on: ubuntu-latest
    steps:
      - uses: sebarickert/financer/.github/actions/static-analyze@test-setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PACKAGE_ROOT: "packages/backend"

  static-analyze-root:
    name: Analyze root
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  static-analyze-playwright:
    name: Analyze playwright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: packages/playwright
