name: Build and publish docker

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Skip frontend css rebuild and use version from repo
        run: 'sed -i ''s/"build": "npm run watch:css && react-scripts build"/"build": "react-scripts build"/g'' frontend/package.json'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTERY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up tags
        id: build-tags
        shell: bash
        run: |
          IMAGE_NAME=ghcr.io/shamalainen/financer
          echo "##[set-output name=BUILD_NUMBER;]$(echo $IMAGE_NAME:${{ github.run_number }})"
          echo "##[set-output name=COMMIT_REF;]$(echo $IMAGE_NAME:$(git rev-parse --short HEAD))"
          echo "##[set-output name=LATEST;]$(echo $IMAGE_NAME:$([[ ${GITHUB_REF#refs/heads/} = "production" ]] && echo "latest" || echo "latest-dev"))"

      - name: Build and publish
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.build-tags.outputs.BUILD_NUMBER }},${{ steps.build-tags.outputs.COMMIT_REF }},${{ steps.build-tags.outputs.LATEST }}
